/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c1c7ce",
        "surface-dim": "#d3ddd0",
        "on-error": "#ffffff",
        "tertiary": "#595f65",
        "surface": "#f2fcef",
        "primary-container": "#41b913",
        "on-primary-fixed": "#052100",
        "primary-fixed": "#84fe59",
        "on-primary-fixed-variant": "#155200",
        "surface-tint": "#1f6d00",
        "outline": "#6e7b66",
        "inverse-on-surface": "#eaf4e7",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#68e03e",
        "on-secondary-fixed": "#001d31",
        "tertiary-fixed": "#dde3ea",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#93ccff",
        "on-surface": "#151e16",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#004b73",
        "inverse-surface": "#2a332a",
        "secondary": "#006397",
        "primary": "#1f6d00",
        "primary-fixed-dim": "#68e03e",
        "surface-container-low": "#ecf6e9",
        "secondary-fixed": "#cce5ff",
        "on-background": "#151e16",
        "on-secondary-container": "#00476e",
        "on-primary-container": "#0f4200",
        "surface-container": "#e7f1e4",
        "background": "#f2fcef",
        "on-surface-variant": "#3f4a38",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#33393e",
        "tertiary-container": "#9ca2a8",
        "error": "#ba1a1a",
        "secondary-container": "#5bb8fe",
        "surface-container-high": "#e1ebde",
        "on-tertiary-fixed-variant": "#41474d",
        "surface-container-highest": "#dbe5d9",
        "on-tertiary-fixed": "#161c21",
        "surface-variant": "#dbe5d9",
        "outline-variant": "#becbb3",
        "surface-bright": "#f2fcef"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
