"""add preferred_language to user

Revision ID: 4ddd31e5ec45
Revises: 379119e7d227
Create Date: 2026-04-10 11:43:20.693603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ddd31e5ec45'
down_revision: Union[str, Sequence[str], None] = '379119e7d227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferred_language')
    # ### end Alembic commands ###
