"""add has_onboarded to user

Revision ID: 6e8664913ef1
Revises: 4ddd31e5ec45
Create Date: 2026-04-10 11:50:04.026343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6e8664913ef1'
down_revision: Union[str, Sequence[str], None] = '4ddd31e5ec45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_onboarded', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_onboarded')
    # ### end Alembic commands ###
