"""add weather and advice to garden

Revision ID: c10f2929c958
Revises: 6e8664913ef1
Create Date: 2026-04-11 18:55:24.245600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c10f2929c958'
down_revision: Union[str, Sequence[str], None] = '6e8664913ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garden', sa.Column('weather_forecast', sa.JSON(), nullable=True))
    op.add_column('garden', sa.Column('smart_advice', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('garden', sa.Column('last_weather_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garden', 'last_weather_update')
    op.drop_column('garden', 'smart_advice')
    op.drop_column('garden', 'weather_forecast')
    # ### end Alembic commands ###
